version: 1

formatters:
  simple:
    format: '%(asctime)-15s -%(name)s -%(process)d-%(levelname)s-%(message)s'
    class: pythonjsonlogger.jsonlogger.JsonFormatter

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  file:
    class: logging.handlers.WatchedFileHandler
    formatter: simple
    mode: a
    filename: './logs/orders-api.log'
  tcp:
    class: logstash_async.handler.AsynchronousLogstashHandler
    level: INFO
    formatter: simple
    host: $LOG_HOST
    port: 9500
    database_path: 'None'

loggers:
  sampleLogger:
    level: DEBUG
    handlers: [console]
    propagate: no
root:
  level: INFO
  handlers: [console, file, tcp]